spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${POSTGRESQL_URL}&currentSchema=money_manager
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}
