spring.application.name=manager

jwt.expiration=${JWT_EXPIRATION:30}
jwt.issuer=${JWT_ISSUER:manager}
jwt.audience=${JWT_AUDIENCE:money-manager-frontend}
jwt.key=${JWT_KEY:9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p3q2r1s0t}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/money_manager}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.profiles.default=${SPRING_PROFILES_DEFAULT:dev}

spring.jackson.deserialization.fail-on-unknown-properties=true

# Explicitly direct Swagger UI to your local OpenAPI schema path
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
