spring.application.name=manager


jwt.expiration=30
jwt.issuer=manager
jwt.audience=money-manager-frontend
jwt.key=9a8b7c6d5e4f3g2h1i0j9k8l7m6n5o4p3q2r1s0t

spring.datasource.url=jdbc:postgresql://localhost:5432/money_manager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jackson.deserialization.fail-on-unknown-properties=true