spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=${DATABASE_URL}?currentSchema=money_manager
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
