openapi: "3.0.3"
info:
  title: API money manager
  version: "1.0"
servers:
  - url: https://api.server.test

tags:
  - name: user
  - name: transaction
  - name: categories
  - name: debts
  - name: payments

paths:
  /user:
    post:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login_success"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /login:
    post:
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/body_login"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login_success"
        "400":
          description: incorrect credentials
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /logout:
    post:
      tags:
        - user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"        
  /user/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - user
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          description: invalid id
        "404":
          description: user not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    put:
      security:
        - bearerAuth: []
      tags:
        - user
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          description: invalid id
        "404":
          description: user not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    delete:
      security:
        - bearerAuth: []
      tags:
        - user
      parameters:
        - name: id
          in: path
          description: user id
          required: true
          schema:
            type: integer      
      responses:
        "200":
          description: user delete
        "400":
          description: invalid id
        "404":
          description: user not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"

  /transaction:
    post: 
      security:
        - bearerAuth: []
      tags:
        - transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/transaction"      
      responses:
        "200":
          description: transaction insert
        "400":
          description: invalid object
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /transactions:
    get:
      security:
        - bearerAuth: []
      tags:
        - transaction
      responses:
        "200":
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /transaction/{id}:
    post:
      security:
        - bearerAuth: []
      tags:
        - transaction
      parameters:
        - name: id
          in: path
          description: transaction id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction"
        "400":
          description: invalid id
        "404":
          description: transaction not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    put:
      security:
        - bearerAuth: []
      tags:
        - transaction
      parameters:
        - name: id
          in: path
          description: transaction id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/transaction"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction"
        "400":
          description: invalid id
        "404":
          description: transaction not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    delete:
      security:
        - bearerAuth: []
      tags:
        - transaction
      parameters:
        - name: id
          in: path
          description: transaction id
          required: true
          schema:
            type: integer      
      responses:
        "200":
          description: transaction delete
        "400":
          description: invalid id
        "404":
          description: transaction not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"

  /category:
    post: 
      security:
        - bearerAuth: []
      tags:
        - categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/categories"      
      responses:
        "200":
          description: category insert
        "400":
          description: invalid object
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /categories:
    get:
      security:
        - bearerAuth: []
      tags:
        - categories
      responses:
        "200":
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/categories"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /category/{id}:
    post:
      security:
        - bearerAuth: []
      tags:
        - categories
      parameters:
        - name: id
          in: path
          description: category id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categories"
        "400":
          description: invalid id
        "404":
          description: category not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    put:
      security:
        - bearerAuth: []
      tags:
        - categories
      parameters:
        - name: id
          in: path
          description: category id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/categories"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categories"
        "400":
          description: invalid id
        "404":
          description: category not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    delete:
      security:
        - bearerAuth: []
      tags:
        - categories
      parameters:
        - name: id
          in: path
          description: category id
          required: true
          schema:
            type: integer      
      responses:
        "200":
          description: category delete
        "400":
          description: invalid id
        "404":
          description: category not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"

  /debt:
    post: 
      security:
        - bearerAuth: []
      tags:
        - debts
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/debts"      
      responses:
        "200":
          description: debt insert
        "400":
          description: invalid object
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /debts:
    get:
      security:
        - bearerAuth: []
      tags:
        - debts
      responses:
        "200":
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/debts"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /debt/{id}:
    post:
      security:
        - bearerAuth: []
      tags:
        - debts
      parameters:
        - name: id
          in: path
          description: debt id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/debts"
        "400":
          description: invalid id
        "404":
          description: debt not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    put:
      security:
        - bearerAuth: []
      tags:
        - debts
      parameters:
        - name: id
          in: path
          description: debt id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/debts"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/debts"
        "400":
          description: invalid id
        "404":
          description: debt not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    delete:
      security:
        - bearerAuth: []
      tags:
        - debts
      parameters:
        - name: id
          in: path
          description: debt id
          required: true
          schema:
            type: integer      
      responses:
        "200":
          description: debt delete
        "400":
          description: invalid id
        "404":
          description: debt not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"

  /payment:
    post: 
      security:
        - bearerAuth: []
      tags:
        - payments
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payments"      
      responses:
        "200":
          description: payment insert
        "400":
          description: invalid object
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /payments:
    get:
      security:
        - bearerAuth: []
      tags:
        - payments
      responses:
        "200":
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/payments"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
  /payment/{id}:
    post:
      security:
        - bearerAuth: []
      tags:
        - payments
      parameters:
        - name: id
          in: path
          description: payment id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payments"
        "400":
          description: invalid id
        "404":
          description: payment not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    put:
      security:
        - bearerAuth: []
      tags:
        - payments
      parameters:
        - name: id
          in: path
          description: payment id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payments"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payments"
        "400":
          description: invalid id
        "404":
          description: payment not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
    delete:
      security:
        - bearerAuth: []
      tags:
        - payments
      parameters:
        - name: id
          in: path
          description: payment id
          required: true
          schema:
            type: integer      
      responses:
        "200":
          description: payment delete
        "400":
          description: invalid id
        "404":
          description: payment not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"                
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    body_login:
      type: object
      properties:
        username:
          type: string
          example: user
        password:
          type: string
          example: 1234
    login_success:
      type: object
      properties:
        token_type:
          type: string
          example: Bearer
        access_token:
          type: string
          example: token
        expires_in:
          type: integer
          example: 18000
    errors:
      type: object
      properties:
        code:
          type: string
          example: error
        message:
          type: string
          example: error
    user:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: username
        password:
          type: string
          example: password
        email:
          type: string
          example: email@gmail.com
    categories:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: videogames
        color:
          type: string
          example: FFFFFF
    transaction:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: name
        transaction_date:
          type: string
          example: "11-12-1999"
        amount:
          type: integer
          example: 2
        price:
          type: number
          example: 10.50
        transaction_type:
          type: string
          example: income
          description: "Enum that only is income or expenses"
        transaction_subtype:
          type: string
          example: variable
          description: "Enum that only is fixed or variable"
        category:
          type: object
          $ref: "#/components/schemas/categories"
    debts:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          description: name
        total_amount:
          type: number 
          description: 10000,29
        start_date:
          type: string
          description: "11-12-1999"
        end_date:
          type: string
          description: "13-12-2000"
    payments:
      type: object
      properties: 
        id:
          type: integer
          example: 1
        payments_date:
          type: string
          example: "20-10-1999"
        amount:
          type: number
          example: 200,45
        debt:
          type: object
          $ref: "#/components/schemas/debts"

security:
  - bearerAuth : []